# Generated by Django 5.1.7 on 2025-04-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('address', models.CharField(max_length=255)),
                ('bedrooms', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('area', models.CharField(max_length=50)),
                ('floor', models.CharField(max_length=50)),
                ('parking', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('adv', 'Apartment'), ('str', 'Villa House'), ('rac', 'Penthouse')], max_length=3)),
                ('image', models.ImageField(upload_to='property_images/')),
            ],
        ),
    ]
