# Generated by Django 5.2 on 2025-05-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0002_contact_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminData',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='appartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(max_length=30)),
                ('address', models.TextField(max_length=200)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('area', models.TextField(max_length=30)),
                ('floor', models.TextField(max_length=20)),
                ('parking', models.TextField(max_length=30)),
                ('image', models.ImageField(upload_to='appartment_images/')),
            ],
        ),
    ]
