# Generated by Django 5.2 on 2025-05-10 20:26

import django.db.models.deletion
import realstateapp.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0003_admindata_appartments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('property_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property_name', models.TextField(max_length=200)),
                ('type', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('area', models.CharField(max_length=100)),
                ('floor', models.CharField(max_length=20)),
                ('parking', models.CharField(max_length=30)),
                ('main_image', models.ImageField(upload_to=realstateapp.models.apartment_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='BrochureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=realstateapp.models.brochure_image_path)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brochure_images', to='realstateapp.apartment')),
            ],
        ),
        migrations.DeleteModel(
            name='appartments',
        ),
    ]
