# Generated by Django 5.2 on 2025-05-11 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0004_apartment_brochureimage_delete_appartments'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='realstateapp.admindata'),
            preserve_default=False,
        ),
    ]
