# Generated by Django 5.2 on 2025-05-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0005_apartment_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='city',
            field=models.TextField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='pincode',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
