# Generated by Django 5.2 on 2025-05-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0006_apartment_city_apartment_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
