# Generated by Django 5.2 on 2025-06-16 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0007_alter_apartment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='status',
            field=models.TextField(default='Active', max_length=10),
        ),
        migrations.CreateModel(
            name='SoldProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=100)),
                ('buyer_address', models.TextField()),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('apartment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='realstateapp.apartment')),
            ],
        ),
    ]
