# Generated by Django 5.2 on 2025-06-24 22:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0008_apartment_status_soldproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('visit_date_str', models.CharField(max_length=100)),
                ('visit_datetime', models.DateTimeField()),
                ('status', models.CharField(default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Scheduled Visit',
                'verbose_name_plural': 'Scheduled Visits',
                'ordering': ['visit_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('addr', models.TextField()),
                ('phn', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.AddField(
            model_name='apartment',
            name='booked_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='parking',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='property_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='status',
            field=models.TextField(default='On Sale', max_length=10),
        ),
        migrations.AddField(
            model_name='scheduledvisit',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='realstateapp.apartment'),
        ),
        migrations.AddField(
            model_name='scheduledvisit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_visits', to='realstateapp.users'),
        ),
    ]
